# TODO: Fix yaml logging config to work
version: 1
formatters:
  standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  error:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: ./data/logs/info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: error
    filename: ./data/logs/error.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  <module>:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]
    propogate: no

  <module.x>:
    level: DEBUG
    handlers: [info_file_handler, error_file_handler]
    propogate: yes

root:
  level: DEBUG
  handlers: [console, info_file_handler]
  propogate: yes
